// Used to categorize items as FRESH PROVISIONS vs PROVISIONS based on keyword matches.

export const NOT_FRESH = [
    'BAKED',
    'CAKE',
    'CAN',
    'COCKTAIL',
    'CREAM',
    'FROZEN',
    'IN CAN',
    'IN TIN',
    'JAM',
    'JUICE',
    'KETCHUP',
    'PASTE',
    'PICKLE',
    'PIE',
    'Q.F',
    'QF',
    'SAUCE',
    'SYRUP',
    'TIN',
    'MILK',
    'POWDER',
    'WHOLE',
    'FLAKES',
    'FLOUR',
    'TEA',
    'BISCUITS',
    'COOKIES',
    'WAFER',
    'CONSERVE'
];


export const FRESH_PROVISIONS_LIST = [
    'AMPALAYA',
    'APPLE',
    'ARTICHOKE',
    'ARUGOLA',
    'ASPARAGUS',
    'AVOCADO',
    'BAK CHOY',
    'BANANA',
    'BASIL',
    'BAY LEAVES',
    'BEANS',
    'BEETROOT',
    'BELL PEPPER',
    'BITTER GOURD',
    'BITTER MELON',
    'BLACKBERRY',
    'BLUEBERRY',
    'BOK CHOI',
    'BOTTLE BRUSH',
    'BRINJAL',
    'BROCCOLI',
    'BRUSSEL SPROUTS',
    'BUTTERNUT',
    'CABBAGE',
    'CALABASA',
    'CAIABASA',
    'CAMOTE',
    'CARROT',
    'CASSAVA',
    'CAULIFLOWER',
    'CELERY',
    'CELERYROOTS',
    'CHARD',
    'CHAYOTE',
    'CHERRIES',
    'CHERRY',
    'CHICORY',
    'CHILLI',
    'CHINESE CABBAGE',
    'CHINESE PECHAY',
    'CHIVE',
    'COCONUT',
    'COOKING BANANA',
    'CORIANDER LEAF',
    'CORIANDER LEAVES',
    'CORN ON THE COB',
    'CORN COB',
    'COURGETTES',
    'COURGETTE',
    'CUCUMBER',
    'CURRY LEAVES',
    'DAIKON',
    'DAYKON',
    'DILL',
    'DRAGON FRUIT',
    'DRUMSTICKS',
    'DRY GARLIC',
    'EGGPLANT',
    'ENDIBE',
    'ENDIVE',
    'ESCAROLE',
    'FENNEL',
    'FIG',
    'FRENCH BEANS',
    'GABI',
    'GARLIC',
    'GINGER',
    'GOLDEN',
    'GRAPE',
    'GREEN BEAN FLAT',
    'GREEN BEAN ROUND',
    'GREEN BEANS',
    'GREEN BEANS HELDA',
    'GREEN BELL PEPPER',
    'GREEN CABBAGE',
    'GREEN CELERY',
    'GREEN CHILLI PEPPERS',
    'GREEN HOT CHILI',
    'GREEN MARROW',
    'GREEN MELON',
    'GREEN PEPPERS',
    'GREEN SALAD PEPPERS ( CAPSICUM )',
    'GUANABANA',
    'GUAVA',
    'GUYABANO',
    'HABANERO CHILI',
    'HONEYDEW MELON',
    'HORSERADISH',
    'ICEBERG LETTUCE',
    'JALAPENO PEPPER',
    'KANG KONG',
    'KIWI',
    'KOHLRABI',
    'KUMERA',
    'LADY FINGER',
    'LEEK',
    'LEMON',
    'LETTUCE',
    'LIME',
    'LONG BEANS',
    'MANDARIN',
    'MANGO',
    'MANIOC',
    'MARROW',
    'MARROWS',
    'MEDLAR',
    'MELON',
    'MINT',
    'MUSHROOM',
    'MURPHY USA',
    'MUSTARD LEAVES',
    'NAPA',
    'NECTARINE',
    'OKRA',
    'ONION',
    'ORANGE',
    'OREGANO',
    'OYSTER MUSHROOMS',
    'PAK CHOI',
    'PAK CHOY',
    'PAPAYA',
    'PARSLEY',
    'PARSNIP',
    'PASSION FRUIT',
    'PAW PAW',
    'PEACH',
    'PEAR',
    'PEAS GREEN',
    'PECHAY',
    'PEPERMINT',
    'PEPPER',
    'PINEAPPLE',
    'PITAHAYA',
    'PLANTAIN',
    'PLUM',
    'POK CHOI',
    'POMEGRANATE',
    'POMEGREANDE',
    'POMELO',
    'POTATO',
    'PUMPKIN',
    'PUMPKIM',
    'RADISH',
    'RADDISH',
    'RAPE VEGETABLE',
    'RASPBERRY',
    'RED APPLES',
    'RED BELL PEPPER',
    'RED CABBAGE',
    'RED CHILLI PEPPERS',
    'RED HOT CHILLI',
    'RED HOT CHILLI SMALL',
    'RED PLUM',
    'RED RADISH',
    'RED SALAD PEPPERS',
    'RED TOMATOES CHERRY IN TRAY 250 GR.',
    'ROCK MELON',
    'ROSEMARY',
    'RUCOLA',
    'SAGE',
    'SAYOTE',
    'SCALLION',
    'SILVER BEETS',
    'SITAW',
    'SNAKE GOURD',
    'SNOW PEAS',
    'SOYBEAN SPROUT',
    'SPANISH SMALL HOT GREEN PEPPERS',
    'SPANSPEK',
    'SPINACH',
    'SPONGE GOURD',
    'SQUASH',
    'STRAWBERRIES',
    'STRAWBERRY',
    'STRING BEANS',
    'SWEET CORN',
    'SWEET MELON',
    'TAMARIND',
    'TANGERINES',
    'TARO',
    'TURMERIC',
    'TEROY',
    'TARRAGON',
    'THYME',
    'TURNIPS',
    'TORONJA',
    'TOFU SOFT X 500 GRM',
    'WATER MELON',
    'WATERCRESS',
    'WATERMELON',
    'YAM',
    'YUCA',
    'ZUCCHINI'
];